version: "3.8"
services:
  postgres:
    container_name: isap.postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=isap
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-docker-postgres
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./src:/app/src

volumes:
  pgdata:
